MultiplicationTableS/Controllers/TableController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using MultiplicationTableS.Models;

namespace MultiplicationTableS.Controllers
{
    /// <summary>
    /// This controller is one of the program controllers that it works on everything for 
    /// designing the multiplication table involving page designing, table designing and 
    /// manipulating, inputs and outputs controling and the related pages views.
    /// </summary>
    public class TableController : Controller
    {
        /// <summary>
        /// This action is the main action of Table controller.
        /// It shows the initiliezed page of the Table controller.
        /// </summary>
        /// <remarks>
        /// This action is a Get type. It is called by clicking on the Multiplication-Table tab.
        /// </remarks>
        /// <returns>
        /// This action returns an object of the Table class and a matrix of the computed 
        /// components of the multiplication table.
        /// </returns>
        [HttpGet]
        public ActionResult Index()
        {
            //Use try-catch block to check of throwing an exception because of an error.
            try
            {
                //Instantiate an object of the Table class using the initilized variables.
                Table table = new Table(10, "decimal");

                //Compute the multiplication table for the first time.
                MultiplicationMatrix multiplicationMatrix = new MultiplicationMatrix(table);

                //Save some variables for transfering them to the view.
                ViewData["table"] = table;
                ViewData["matrix"] = multiplicationMatrix.matrixComponents;
            }
            catch (InvalidDataException ex)
            {
                //Make a message and a javascript alert function when we have a thrown exception.
                //This function will show an error message to user on the client side.
                string message = "<script>alert('Error in input data: " + ex.Message
                    + "');</script>";

                //Write the javascript function in the client side (Fron-End) of the program.
                Response.Write(message);
            }
            return View();
        }

        /// <summary>
        /// This action works on getting some variables from the view, instantiating an 
        /// object of the Table class, computing the multiplication table and transfering some 
        /// variables to the view, and also shows the multiplication-table page.
        /// </summary>
        /// <remarks>
        /// This action is a Post type  and is called by submitting the form in the view page.
        /// </remarks>
        /// <param name="tableIn"> An object of the Table class with two variables.</param>
        /// <returns>
        /// This action returns an object of the Table class and a matrix of the computed 
        /// components of the multiplication table.
        /// </returns>
        [HttpPost]
        public ActionResult Index(Table tableIn)
        {
            //Use try-catch block to check of throwing an exception because of an error.
            try
            {
                //Instantiate an object of the Table class using the variables coming from the view.
                Table table = new Table(tableIn.MatrixSize, tableIn.MatrixBase);

                //Compute the multiplication table using the variables coming from the view.
                MultiplicationMatrix multiplicationMatrix = new MultiplicationMatrix(table);

                //Save some variables for transfering them to the view.
                ViewData["table"] = table;
                ViewData["matrix"] = multiplicationMatrix.matrixComponents;
            }
            catch (InvalidDataException ex)
            {
                //Make a message and a javascript alert function when we have a thrown exception.
                //This function will show an error message to user on the client side.
                string message = "<script>alert('Error in input data: " + ex.Message
                    + "');</script>";

                //Write the javascript function in the client side (Fron-End) of the program.
                Response.Write(message);
            }
            return View();
        }

        /// <summary>
        /// This action works on getting some variables from the view, instantiating an 
        /// object of the Table class, compute the multiplication table and transfering some 
        /// variables to the view, and also show the multiplication-table page.
        /// </summary>
        /// <remarks>
        /// This action is a Get type and is called by selecting the multiplication-table 
        /// in the view page.
        /// </remarks>
        /// <param name="size"> The size of the multiplication table.</param>
        /// <param name="mbase"> The base of the multiplication table.</param>
        /// <returns>
        /// This action returns an object of the Table class and a matrix of the computed 
        /// components of the multiplication table.
        /// </returns>
        [HttpGet]
        public ActionResult Index1(int size, string mbase)
        {
            //Use try-catch block to check of throwing an exception because of an error.
            try
            {
                //Instantiate an object of the Table class using the variables coming from the view.
                Table table = new Table(size, mbase);

                //Compute the multiplication table using the variables coming from the view.
                MultiplicationMatrix multiplicationMatrix = new MultiplicationMatrix(table);

                //Save some variables for transfering them to the view.
                ViewData["table"] = table;
                ViewData["matrix"] = multiplicationMatrix.matrixComponents;
            }
            catch (InvalidDataException ex)
            {
                //Make a message and a javascript alert function when we have a thrown exception.
                //This function will show an error message to user on the client side.
                string message = "<script>alert('Error in input data: " + ex.Message
                    + "');</script>";

                //Write the javascript function in the client side (Fron-End) of the program.
                Response.Write(message);
            }
            return View("~/Views/Table/Index.cshtml");
        }
    }
}

MultiplicationTableS/Views/Table/Index.cshtml
@using MultiplicationTableS.Models
@model Table

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Table Show";
    var table = (Table)ViewData["table"];
    var matrix = (List<List<string>>)ViewData["matrix"];
}

@section Styles
{
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css" />
}

@section Scripts
{
    <script>
        //Save some ASP .NET variables in the Javascript variables to be used in the table.js.
        var base = "@table.MatrixBase";
        var size2 = @table.MatrixSize;

        var matrix2 = [];
        @{
            foreach (var row in matrix)
            {
                @:var matrix1 = [];
                foreach (var str in row)
                {
                  @:matrix1.push("@str");
                }
                @:matrix2.push(matrix1);
            }
        }

        //Define a Javascript function for going the program to the get method of the Index
        //in Table controller by clicking on the multiplication table.
        $('#multi').on("click", function () {
            var size1 = $('#MatrixSize').val();
            var base1 = $('#select').val();

            var url1 = '@Html.Raw(Url.Action("Index1", "Table", new { size = "s1", mbase = "b1" }))';
            var url2 = url1.replace('s1', size1);
            var url  = url2.replace('b1', base1);
            window.location.href = url;
        });
    </script>

    <script src="~/Scripts/table.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
}

<div class="row">
    <div class="col-sm-9 col-md-9" style="text-align: center">
        <h2>Multiplication Table Show</h2>
    </div>
</div>
<div class="row">
    <div class="col-sm-9 col-md-9" style="text-align: center">
        <hr />
    </div>
</div>

<div class="row">
    <div class="col-sm-9 col-md-9">
        <h3>Multiplication-Table Inputs:</h3>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12">
        <form method="post" action="~/Table/Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-4 col-sm-3 col-md-3">
                    <div class="form-group">
                        @Html.LabelFor(model => model.MatrixSize, new { htmlAttributes = new { @class = "control-label" } })
                        <input type="number" name="MatrixSize" asp-for="MatrixSize" id="MatrixSize" class="form-control" value="@table.MatrixSize" />
                        <span asp-validation-for="MatrixSize" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4 col-sm-3 col-md-3">
                    <div class="form-group">
                        @Html.LabelFor(model => model.MatrixBase, new { htmlAttributes = new { @class = "control-label" } })
                        <select name="MatrixBase" asp-for="MatrixBase" class="form-control" id="select" value="@table.MatrixBase">
                            <option value="decimal">Decimal</option>
                            <option value="binary">Binary</option>
                            <option value="hex">Hexadecimal </option>
                        </select>
                        <span asp-validation-for="MatrixBase" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-8 col-sm-8 col-md-6">
                    <div class="form-group">
                        <label class="control-label">Klick on the Button or Select the Table</label>
                        <br />
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-9 col-sm-9 col-md-8">
        <table id="multi" class="col-9 col-sm-9 col-md-8">
            @{
                <tr>
                    @{
                        for (int j = 0; j <= table.MatrixSize; j++)
                        {
                            <td>@matrix[0][j]</td>
                        }
                    }
                </tr>
            }
            @{
                for (int i = 1; i <= table.MatrixSize; i++)
                {
                    <tr>
                        @{
                            <td>@matrix[i][0]</td>
                            for (int j = 1; j <= table.MatrixSize; j++)
                            {
                                <td title="" class="tdTable">@matrix[i][j]</td>
                            }
                        }
                    </tr>
                }
            }
        </table>
    </div>
</div>